### ISSUE TITLE
Classes without interface

### ISSUE THREAD

**Issue by Nickman87** [JonPSmith/NetCore.AutoRegisterDi#10]
As far as I can tell, the tool does not register classes that have no interface?

I can imagine that in most codebases, and for DI to be used to its fullest, you would define interfaces for most of the classes you want to inject. But it might be useful to also support (perhaps trough a setting) adding classes without interfaces to the DI chain?

Is this something you would consider or are there reasons not to support this?

**Comment by JonPSmith** [comment]
Hi @Nickman87,

Yes, some classes are registered directly but they are rare or have a specific way to register, e.g. registering an EF Core DbContext. I _could_ add something to mark classes but I don't think many people would use it. 

This library is super-simple, which I makes it easy to understand / use. I few people have suggested adding extra code and I have suggested they look at [Scrutor](https://github.com/khellang/Scrutor) library which lots of options - maybe there is something that would help you with registering classes.

**Comment by Grauenwolf** [comment]
Unfortunately this makes it unusable for me. The project I'm working on has banned shadow interfaces (and mock tests) so we really need a `.AsPublicClasses` option.

**Comment by JonPSmith** [comment]
Hi @Grauenwolf,

Sorry this code doesn't work for you, but because the code is a MIT License (and very small) so could copy the code and add extra features bits you want.
