### ISSUE TITLE
How to use without Interface?

### ISSUE THREAD

**Issue by mammadkoma** [JonPSmith/NetCore.AutoRegisterDi#11]
Hello and thank you for this package
If I inheritance UserService from IUserService this code in Program.cs inject UserService into UserController correctly:
```
builder.Services.RegisterAssemblyPublicNonGenericClasses()
  .Where(c => c.Name.EndsWith("Service"))
  .AsPublicImplementedInterfaces(ServiceLifetime.Scoped);
```

`public class UserService : IUserService`

```
private readonly IUserService _userService;
public UserController(IUserService userService)
{
    _userService = userService;
}
```

But I want to inject UserService to UserController (not IUserService)
```
public class UserService //: IUserService
{
    private readonly AppDbContext _db;

    public UserService(AppDbContext appDbContext)
    {
        _db = appDbContext;
    }
```
```
public class UserController : ControllerBase
{
    private readonly UserService _userService;
    public UserController(UserService userService)
    {
        _userService = userService;
    }
```
Then  I get this error in swagger : 
"Unable to resolve service for type 'WebApi.Services.UserService.UserService' while attempting to activate 'WebApi.Controllers.UserController.UserController'."

**Comment by JonPSmith** [comment]
Hi @mammadkoma,

This library only registers classes that have a interface. Sure, I could add classes but there is so many ways that this could register too many classes and making it full proof would be hard.

You might like to look at [Scrutor](https://github.com/khellang/Scrutor), which has a way to register classes as explained by [Andrew Lock's article](https://andrewlock.net/using-scrutor-to-automatically-register-your-services-with-the-asp-net-core-di-container/#registering-implementations-as-a-service).

**Comment by mammadkoma** [comment]
```
var appServices = typeof(Program).Assembly.GetTypes()
    .Where(s => s.Name.EndsWith("Service") && s.IsInterface == false).ToList();
foreach (var appService in appServices)
    builder.Services.Add(new ServiceDescriptor(appService, appService, ServiceLifetime.Scoped));
```

I don't write interface for my services (for writing less code).

These codes find all Types with these conditions : be class and not interface and EndsWith : "Service".

Then add all service classes to the .net DI container.

https://github.com/mammadkoma/webapi/blob/master/WebApi/Program.cs
