### ISSUE TITLE
GetService based on Class Type instead of Interface

### ISSUE THREAD

**Issue by panosru** [JonPSmith/NetCore.AutoRegisterDi#4]
Hello, I'm not sure if I'm doing something wrong or if it is how `AutoRegisterDi` should work, but I have the following *issue*:

```csharp
ServiceLocator.ServiceContainer.GetService<T>(Type type);
```

The method above brings me the services I have registered in my service container, basically, it is a proxy for `IHttpContextAccessor`.

In my project I have some classes like this one *(code trimmed)*:

```csharp
public class GetAllUseCase : UseCase<IGetAllOutput>
{
    protected override async Task Execute()
    {
        // voodoo
    }
}

public class ForecastUseCase : UseCase<IForecastOutput>
{
    protected override async Task Execute()
    {
        // voodoo
    }
}
```

Basically I have a bunch of classes with `UseCase` suffix. The way I register them now is `services.AddScoped(typeof(GetAllUseCase));`, that is a) in order to avoid long generic interfaces and b) when I inject the class into the needed class it goes like so:

```csharp
public class Weather : ApiController
{
    private readonly ForecastUseCase _useCase;

    public Weather([FromServices] ForecastUseCase useCase) => _useCase = useCase;
```

So far so good, what I expected with AutoRegisterDi was something like this:

```
services.RegisterAssemblyPublicNonGenericClasses(typeof(ForecastUseCase).Assembly)
    .Where(c => c.Name.EndsWith("UseCase"));
```

I tried also with `.AsPublicImplementedInterfaces()`, but it didn't work. 

To simplify things I have the following:

```csharp
public interface IFoobar<T>
{ }

public class Foobar : IFoobar<string>
{
    public string Foo { get; } = "Foo";
    
    public string Bar { get; } = "Bar";
}
```
*Obviously the generic type here has no practical reason, it is just for depo purposes*

and I saw that if I try to call by interface like so:

```csharp
var foobar = ServiceLocator.ServiceContainer.GetService<IFoobar<string>>(
                typeof(IFoobar<string>));
```

it works, but if I call it by class it doesn't:

```chsarp
var foobar = ServiceLocator.ServiceContainer.GetService<Foobar>(
                typeof(Foobar));
```

Could you suggest me a way to make it so it will work by calling either the interface or the class directly if that is possible of course?

Thanks!

**Comment by JonPSmith** [comment]
Hi @panosru,

I'm sorry but NetCore.AutoRegisterDi does't register generic classes. That fact was buried in the readme file, so I have updated the readme with a link to the excluded class types. 

You have to manually your generic classes.
