### ISSUE TITLE
Multiple implementation of a single interface

### ISSUE THREAD

**Issue by parikshitphukan17** [JonPSmith/NetCore.AutoRegisterDi#6]
If 2 classes were to implement the same interface, how are we to differentiate between the 2 implementations?

**Comment by parikshitphukan17** [comment]
[https://www.stevejgordon.co.uk/asp-net-core-dependency-injection-registering-multiple-implementations-interface](url)
Can something like this be implemented in this?

**Comment by JonPSmith** [comment]
Hi @parikshitphukan17,

The question you are asking is a dependency injection (DI) issue. The problem isn't with the registering, but how you access them.

So, if you have multiple classes with the same interface, then NetCore.AutoRegisterDi will register each one. But when you want to access them, then you need to get all the implementations. Steve Gordon's article shows one way, `IEnumerable<IEnricher> enrichers`. The other way is to access the DI provider directly, e.g. `services.GetServices<IEnricher>()` which will returns `IEnumerable<IEnricher>`.

I hope that helps.
