### ISSUE TITLE
Extensions.AssertExtensions as a package?

### ISSUE THREAD

**Issue by coderdnewbie** [JonPSmith/NetCore.AutoRegisterDi#7]
Extensions.AssertExtensions is very useful set of xunit extensions. Perhaps you should make this a separate package for all xunit users to use?

Looks very useful to me.

**Comment by JonPSmith** [comment]
Hi @coderdnewbie,

I have a library called [EfCore.TestSupport](https://www.nuget.org/packages/EfCore.TestSupport/) which has those assertions plus other code to help in unit testing EF Core. Be warned: I'm putting out a new version of this libaray in two or three week's time. assertions don't change but the EF Core stuff changes a LOT.
